import { ingredientNameKey } from '@/features/ingredients/parse-ingredient-line';

/**
 * Standard grocery categories. Every ingredient has one; each store area says
 * which categories it holds, so an ingredient's area in any store follows
 * from its category unless she overrides it for that store.
 */
export const CATEGORIES = [
  { id: 'produce', name: 'Produce' },
  { id: 'bakery', name: 'Bakery & Bread' },
  { id: 'deli', name: 'Deli' },
  { id: 'meat-seafood', name: 'Meat & Seafood' },
  { id: 'dairy-eggs', name: 'Dairy & Eggs' },
  { id: 'frozen', name: 'Frozen' },
  { id: 'pantry-canned', name: 'Pantry & Canned' },
  { id: 'baking-spices', name: 'Baking & Spices' },
  { id: 'snacks', name: 'Snacks' },
  { id: 'beverages', name: 'Beverages' },
  { id: 'household', name: 'Household' },
  { id: 'other', name: 'Other' },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]['id'];

export function isCategoryId(value: unknown): value is CategoryId {
  return CATEGORIES.some((c) => c.id === value);
}

export function categoryName(id: CategoryId): string {
  return CATEGORIES.find((c) => c.id === id)?.name ?? 'Other';
}

/** Common ingredients by category (names are matched with ingredientNameKey). */
const KNOWN: Record<CategoryId, string[]> = {
  produce: [
    'onion',
    'yellow onion',
    'white onion',
    'red onion',
    'sweet onion',
    'green onion',
    'scallion',
    'shallot',
    'leek',
    'garlic',
    'garlic clove',
    'ginger',
    'potato',
    'russet potato',
    'yukon gold potato',
    'red potato',
    'sweet potato',
    'yam',
    'carrot',
    'baby carrot',
    'celery',
    'tomato',
    'roma tomato',
    'cherry tomato',
    'grape tomato',
    'lettuce',
    'romaine lettuce',
    'iceberg lettuce',
    'spinach',
    'baby spinach',
    'kale',
    'arugula',
    'spring mix',
    'cabbage',
    'red cabbage',
    'broccoli',
    'cauliflower',
    'zucchini',
    'yellow squash',
    'butternut squash',
    'spaghetti squash',
    'cucumber',
    'bell pepper',
    'red bell pepper',
    'green bell pepper',
    'yellow bell pepper',
    'jalapeno',
    'jalapeño',
    'poblano pepper',
    'serrano pepper',
    'mushroom',
    'cremini mushroom',
    'portobello mushroom',
    'asparagus',
    'green bean',
    'corn',
    'corn on the cob',
    'pea',
    'snap pea',
    'eggplant',
    'avocado',
    'lemon',
    'lime',
    'orange',
    'apple',
    'banana',
    'strawberry',
    'blueberry',
    'raspberry',
    'blackberry',
    'grape',
    'peach',
    'pear',
    'pineapple',
    'mango',
    'watermelon',
    'cantaloupe',
    'kiwi',
    'cilantro',
    'parsley',
    'italian parsley',
    'basil',
    'fresh basil',
    'mint',
    'dill',
    'rosemary',
    'thyme',
    'sage',
    'chive',
    'radish',
    'beet',
    'bean sprout',
    'bok choy',
  ],
  bakery: [
    'bread',
    'white bread',
    'wheat bread',
    'sourdough bread',
    'french bread',
    'baguette',
    'hamburger bun',
    'hot dog bun',
    'bun',
    'roll',
    'dinner roll',
    'bagel',
    'english muffin',
    'tortilla',
    'flour tortilla',
    'corn tortilla',
    'pita',
    'naan',
    'croissant',
    'muffin',
    'hoagie roll',
    'slider bun',
  ],
  deli: [
    'deli turkey',
    'sliced turkey',
    'deli ham',
    'sliced ham',
    'salami',
    'pepperoni',
    'rotisserie chicken',
    'hummus',
    'prosciutto',
  ],
  'meat-seafood': [
    'chicken',
    'chicken breast',
    'boneless skinless chicken breast',
    'chicken thigh',
    'boneless skinless chicken thigh',
    'chicken drumstick',
    'chicken wing',
    'whole chicken',
    'ground chicken',
    'ground turkey',
    'turkey',
    'ground beef',
    'lean ground beef',
    'beef',
    'stew meat',
    'beef stew meat',
    'chuck roast',
    'roast',
    'steak',
    'flank steak',
    'sirloin steak',
    'ribeye',
    'brisket',
    'pork',
    'pork chop',
    'pork loin',
    'pork tenderloin',
    'pork shoulder',
    'ground pork',
    'bacon',
    'sausage',
    'italian sausage',
    'breakfast sausage',
    'ham',
    'salmon',
    'salmon fillet',
    'tilapia',
    'cod',
    'halibut',
    'shrimp',
    'tuna steak',
    'scallop',
    'crab',
    'lobster',
  ],
  'dairy-eggs': [
    'milk',
    'whole milk',
    '2% milk',
    'skim milk',
    'buttermilk',
    'heavy cream',
    'heavy whipping cream',
    'whipping cream',
    'half-and-half',
    'sour cream',
    'cream cheese',
    'butter',
    'unsalted butter',
    'salted butter',
    'margarine',
    'egg',
    'large egg',
    'egg white',
    'yogurt',
    'greek yogurt',
    'cottage cheese',
    'ricotta',
    'ricotta cheese',
    'cheese',
    'cheddar',
    'cheddar cheese',
    'shredded cheddar',
    'sharp cheddar',
    'mozzarella',
    'mozzarella cheese',
    'shredded mozzarella',
    'parmesan',
    'parmesan cheese',
    'feta',
    'feta cheese',
    'monterey jack',
    'pepper jack',
    'swiss cheese',
    'provolone',
    'colby jack',
    'mexican blend cheese',
    'string cheese',
    'whipped cream',
  ],
  frozen: [
    'frozen pea',
    'frozen corn',
    'frozen broccoli',
    'frozen spinach',
    'frozen mixed vegetable',
    'frozen berry',
    'frozen strawberry',
    'frozen blueberry',
    'ice cream',
    'frozen pizza',
    'frozen waffle',
    'tater tot',
    'french fry',
    'frozen shrimp',
    'pie crust',
  ],
  'pantry-canned': [
    'rice',
    'white rice',
    'brown rice',
    'jasmine rice',
    'basmati rice',
    'pasta',
    'spaghetti',
    'penne',
    'macaroni',
    'elbow macaroni',
    'fettuccine',
    'linguine',
    'lasagna noodle',
    'egg noodle',
    'ramen',
    'quinoa',
    'couscous',
    'oat',
    'rolled oat',
    'oatmeal',
    'cereal',
    'black bean',
    'kidney bean',
    'pinto bean',
    'cannellini bean',
    'garbanzo bean',
    'chickpea',
    'refried bean',
    'lentil',
    'diced tomato',
    'crushed tomato',
    'tomato sauce',
    'tomato paste',
    'marinara',
    'marinara sauce',
    'pasta sauce',
    'salsa',
    'enchilada sauce',
    'red enchilada sauce',
    'green enchilada sauce',
    'chicken broth',
    'beef broth',
    'vegetable broth',
    'chicken stock',
    'beef stock',
    'cream of chicken soup',
    'cream of mushroom soup',
    'coconut milk',
    'tuna',
    'canned tuna',
    'peanut butter',
    'jam',
    'jelly',
    'honey',
    'maple syrup',
    'olive oil',
    'extra virgin olive oil',
    'vegetable oil',
    'canola oil',
    'coconut oil',
    'sesame oil',
    'cooking spray',
    'vinegar',
    'white vinegar',
    'apple cider vinegar',
    'balsamic vinegar',
    'red wine vinegar',
    'rice vinegar',
    'soy sauce',
    'worcestershire sauce',
    'hot sauce',
    'sriracha',
    'ketchup',
    'mustard',
    'dijon mustard',
    'mayonnaise',
    'mayo',
    'barbecue sauce',
    'bbq sauce',
    'ranch dressing',
    'italian dressing',
    'teriyaki sauce',
    'hoisin sauce',
    'fish sauce',
    'green chile',
    'diced green chile',
    'chipotle in adobo',
    'olive',
    'black olive',
    'pickle',
    'breadcrumb',
    'panko',
    'crouton',
    'taco shell',
  ],
  'baking-spices': [
    'flour',
    'all-purpose flour',
    'bread flour',
    'whole wheat flour',
    'sugar',
    'granulated sugar',
    'brown sugar',
    'powdered sugar',
    "confectioners' sugar",
    'baking soda',
    'baking powder',
    'yeast',
    'active dry yeast',
    'cornstarch',
    'cocoa powder',
    'chocolate chip',
    'semi-sweet chocolate chip',
    'vanilla',
    'vanilla extract',
    'almond extract',
    'salt',
    'kosher salt',
    'sea salt',
    'pepper',
    'black pepper',
    'ground black pepper',
    'garlic powder',
    'onion powder',
    'paprika',
    'smoked paprika',
    'chili powder',
    'cumin',
    'ground cumin',
    'oregano',
    'dried oregano',
    'basil leaves',
    'dried basil',
    'dried thyme',
    'italian seasoning',
    'cinnamon',
    'ground cinnamon',
    'nutmeg',
    'ginger powder',
    'ground ginger',
    'cayenne',
    'cayenne pepper',
    'red pepper flake',
    'crushed red pepper',
    'bay leaf',
    'taco seasoning',
    'curry powder',
    'turmeric',
    'garam masala',
    'seasoning salt',
    'ranch seasoning',
    'sprinkle',
    'food coloring',
    'shortening',
    'walnut',
    'pecan',
    'almond',
    'sliced almond',
    'raisin',
    'coconut',
    'shredded coconut',
    'graham cracker',
  ],
  snacks: ['chip', 'tortilla chip', 'potato chip', 'cracker', 'pretzel', 'popcorn', 'granola bar'],
  beverages: [
    'water',
    'sparkling water',
    'juice',
    'orange juice',
    'apple juice',
    'lemonade',
    'coffee',
    'tea',
    'soda',
    'white wine',
    'red wine',
    'beer',
  ],
  household: [
    'aluminum foil',
    'foil',
    'plastic wrap',
    'parchment paper',
    'paper towel',
    'napkin',
    'trash bag',
    'zip-top bag',
    'dish soap',
  ],
  other: [],
};

const KNOWN_BY_KEY = new Map<string, CategoryId>();
for (const [category, names] of Object.entries(KNOWN) as [CategoryId, string[]][]) {
  for (const name of names) KNOWN_BY_KEY.set(ingredientNameKey(name), category);
}

/** Single words that decide the category when the full name isn't known. */
const KEYWORDS: [RegExp, CategoryId][] = [
  [/\bfrozen\b/, 'frozen'],
  [/\b(canned|can of)\b/, 'pantry-canned'],
  [/\b(cheese|cheddar|mozzarella|parmesan|milk|butter|yogurt|cream|egg)\b/, 'dairy-eggs'],
  [
    /\b(chicken|beef|pork|turkey|sausage|bacon|steak|salmon|shrimp|fish|fillet|roast|lamb)\b/,
    'meat-seafood',
  ],
  [/\b(bread|bun|roll|bagel|tortilla|baguette|muffin)\b/, 'bakery'],
  [/\b(broth|stock|sauce|soup|bean|pasta|noodle|rice|oil|vinegar|dressing)\b/, 'pantry-canned'],
  [/\b(flour|sugar|extract|seasoning|powder|spice|dried|ground)\b/, 'baking-spices'],
  [/\b(lettuce|onion|pepper|tomato|potato|squash|berry|apple|herb|fresh)\b/, 'produce'],
  [/\b(chip|cracker|cookie)\b/, 'snacks'],
  [/\b(juice|soda|wine|beer|coffee|tea)\b/, 'beverages'],
];

/**
 * Best-guess category for an ingredient name: the built-in list first (also
 * trying the name without leading words, so "diced yellow onion" finds
 * "yellow onion"), then keywords, else "other".
 */
export function guessCategory(name: string): CategoryId {
  const key = ingredientNameKey(name);
  const words = key.split(' ');
  for (let start = 0; start < words.length; start++) {
    const match = KNOWN_BY_KEY.get(words.slice(start).join(' '));
    if (match) return match;
  }
  for (const [pattern, category] of KEYWORDS) {
    if (pattern.test(key)) return category;
  }
  return 'other';
}
